#define HAVE_SYS_RESOURCE_H 1
#define HAVE_GETRUSAGE 1

#define HAVE_ATTRIBUTE_PACKED 1
/* #undef HAVE_PRAGMA_PACK */
#define HAVE_ATTRIBUTE_ALIGNED 1
/* #undef HAVE_DECLSPEC_ALIGN */
/* #undef HAVE_DECLSPEC_DLLEXPORT */
/* #undef HAVE_LIBREADLINE */
#define HAVE_NETINET_IN_H 1

#define HAVE_LIBRT 1
